# Generated by Django 5.2.8 on 2025-11-26 16:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('emp_id', models.CharField(help_text='Unique identifier for the employee', max_length=20, unique=True, verbose_name='Employee ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('address', models.TextField(max_length=500, verbose_name='Full Address')),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('MARKETING', 'Marketing'), ('SALES', 'Sales'), ('OPERATIONS', 'Operations'), ('ENGINEERING', 'Engineering'), ('SUPPORT', 'Customer Support')], max_length=50, verbose_name='Department')),
                ('position', models.CharField(max_length=200, verbose_name='Job Position')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Salary')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20, verbose_name='Employment Status')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Record Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='emp.employee', verbose_name='Reporting Manager')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['emp_id'], name='emp_employe_emp_id_57eca7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='emp_employe_departm_2d8d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='emp_employe_status_ddb771_idx'),
        ),
    ]
