# Generated by Django 6.0 on 2026-01-18 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Log Level')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('message', models.TextField(verbose_name='Message')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback')),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='utils_syste_created_0c8785_idx'), models.Index(fields=['level'], name='utils_syste_level_d90b89_idx'), models.Index(fields=['source'], name='utils_syste_source_2a5acb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('system', 'System Event'), ('error', 'Error')], max_length=20, verbose_name='Log Type')),
                ('module', models.CharField(choices=[('employee', 'Employee'), ('department', 'Department'), ('user', 'User'), ('system', 'System'), ('authentication', 'Authentication'), ('report', 'Report')], max_length=20, verbose_name='Module')),
                ('action', models.TextField(verbose_name='Action Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=20, verbose_name='Status')),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='utils_activ_created_a993c5_idx'), models.Index(fields=['user'], name='utils_activ_user_id_3622e9_idx'), models.Index(fields=['log_type'], name='utils_activ_log_typ_e49f62_idx'), models.Index(fields=['module'], name='utils_activ_module_0b8612_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore')], max_length=40, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(max_length=100, verbose_name='Object ID')),
                ('object_repr', models.TextField(verbose_name='Object Representation')),
                ('changes', models.JSONField(default=dict, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='utils_audit_created_aa8961_idx'), models.Index(fields=['user'], name='utils_audit_user_id_556b53_idx'), models.Index(fields=['model_name'], name='utils_audit_model_n_c38f43_idx'), models.Index(fields=['action'], name='utils_audit_action_1d6570_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('locked', 'Account Locked'), ('expired', 'Password Expired')], max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('failure_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Failure Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='utils_login_created_fb98be_idx'), models.Index(fields=['username'], name='utils_login_usernam_789be8_idx'), models.Index(fields=['status'], name='utils_login_status_a9c311_idx'), models.Index(fields=['ip_address'], name='utils_login_ip_addr_73ee20_idx')],
            },
        ),
    ]
